### ISSUE TITLE
La descripción de desconferencias distorcionadas

### ISSUE THREAD

**Issue by ecabrerar** [BarcampRD/barcamp2018#2]
En años anteriores teníamos filas de 3 columnas, ahora con fila de 4 columnas, la descripción sale distorsionada. Ocultar la descripción en esa página y mostrarla al pulsar algún botón. Pueden tomar como referencia los Popovers de bootstrap https://getbootstrap.com/docs/4.1/components/popovers/
![screenshot_2018-11-01-barcamp](https://user-images.githubusercontent.com/2789130/47858632-e7f83f00-ddc2-11e8-9288-1c5454dc371a.png)

Que opinas @vacax ?

**Comment by vacax** [comment]
Caso trabajado en su momento.
